version: '2.23.0'

services:
  maria_db:
    build:
      context: .
      dockerfile: maria_db.dockerfile
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - DATABASE_USERNAME
      - MARIADB_ROOT_PASSWORD
    networks:
      app-network:
        ipv4_address: 172.20.1.3
    expose:
      - "3306"
    tty: true

  codelab:
    build:
      context: .
      dockerfile: application.dockerfile
    ports:
      - "8080:8080"
    networks:
      app-network:
        ipv4_address: 172.20.1.2
    environment:
      - DATABASE_URL
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
    depends_on:
      - maria_db

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.1.0/24

volumes:
  db_data: